#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

function ctrl_c(){
  echo -e "\n\n${redColour}[!] Saliendo ...${endColour}\n "
  tput cnorm && exit 1 
}

clear
#CTRL_C
trap ctrl_c INT
 
function helpPanel(){
 echo -e "\n${yellowColour}[+]${endColour}${grayColour} Ayuda${endColour}${purpleColour} $0${grayColour} --> ${greenColour}example: ./ruleta.sh -m 1000 -t martingala${endColour}\n"
 echo -e "\t${blueColour}-m)${endColour}${grayColour} Dinero con el que se juega${endColour}"
 echo -e "\t$blueColour-t)${endColour}${grayColour} Técnica a utilizar ${blueColour}(martingala/inverselaubruchere)${endColour}"
}

function martingala(){
 echo -e "\n${yellowColour}[+]${endColour}${grayColour} Dinero actual:${endColour}${yellowColour} $money€${endColour}"
 echo -ne "${yellowColour}[+]${endColour}${grayColour} Cuánto dinero tienes pensado apostar? -> ${endColour}"${purpleColour} && read initial_bet
 echo -ne "${yellowColour}[+]${grayColour} ¿A qué deseas apostar continuamente (par/impar? -> "${greenColour}   && read par_impar

 echo -e "\n${yellowColour}[+]${grayColour} Vamos a jugar con una cantidad inicial de${purpleColour} $initial_bet€${grayColour} a${greenColour} $par_impar${endColour}"

 maxmoney=" "
 backup_bet=$initial_bet 
 play_counter=0
 jugadas_malas=" "

  tput civis
  while true; do
    money=$(($money-$initial_bet))
    echo -e "\n${yellowColour}[+]${grayColour} Acabas de apostar ${yellowColour}$initial_bet€${grayColour} y tienes ${yellowColour}$money€${endColour}"
    random_number="$((RANDOM % 37))"
    echo -e "${yellowColour}[+]${grayColour} Ha salido el número${blueColour} $random_number${endColour}"
    
    if [ ! "$money" -lt 0 ]; then
      if [ "$par_impar" == "par" ]; then 
        if [ "$(($random_number % 2))" -eq 0 ]; then
          if [ "$random_number" -eq 0 ]; then
            echo -e "${yellowColour}[+]${grayColour} Ha salido el 0, por tanto perdemos${endColour}"
            initial_bet=$(($initial_bet*2))
            echo -e "${redColour}[-]${grayColour} Te queda un total de${redColour} $money€${endColour}"
            jugadas_malas+="$random_number "
           else
            echo -e "${yellowColour}[+]${grayColour} El número que ha salido es par.${greenColour} ¡¡GANAS!!${endColour}"
            reward=$(($initial_bet*2))
            echo -e "${yellowColour}[+]${grayColour} Ganas un total de ${greenColour}$reward€${endColour}"
            money=$(($money+$reward))
            echo -e "${yellowColour}[+]${grayColour} Tienes un total de ${turquoiseColour}$money€${endColour}"
            initial_bet=$backup_bet
            jugadas_malas=""
            maxmoney=$money
          fi
        else
          echo -e "${yellowColour}[+]${grayColour} El número que ha salido es impar. ${redColour}¡¡PIERDES!!${endColour}"
          initial_bet=$(($initial_bet*2))
          jugadas_malas+="$random_number "
          echo -e "${redColour}[-]${grayColour} Te queda un total de${redColour} $money€${endColour}"      
        fi
      else
        if [ "$(($random_number % 2))" -eq 1 ]; then
          echo -e "${yellowColour}[+]${grayColour} El número que ha salido es impar.${greenColour} ¡¡GANAS!!${endColour}"
          reward=$(($initial_bet*2))
          echo -e "${yellowColour}[+]${grayColour} Ganas un total de ${greenColour}$reward€${endColour}"
          money=$(($money+$reward))
          echo -e "${yellowColour}[+]${grayColour} Tienes un total de ${turquoiseColour}$money€${endColour}"
          initial_bet=$backup_bet
          jugadas_malas=""
          maxmoney=$money
      else
        echo -e "${yellowColour}[+]${grayColour} El número que ha salido es par. ${redColour}¡¡PIERDES!!${endColour}"
        initial_bet=$(($initial_bet*2))
        jugadas_malas+="$random_number "
        echo -e "${redColour}[-]${grayColour} Te queda un total de${redColour} $money€${endColour}"      
       fi
      fi
clear
    else
      echo -e "\n${redColour}[!] Te has quedado sin pasta cabrón${endColour}"
      echo -e "${yellowColour}[+]${grayColour} Han habido un total de ${yellowColour}$play_counter ${grayColour}jugadas${endColour}"
      echo -e "${yellowColour}[+]${grayColour} A continuación se van a representar las malas jugadas consecutivas que han salido:${endColour}\n"
      echo -e "${blueColour}[ $jugadas_malas]${endColour}"
      echo -e "\n${yellowColour}[*]${endColour}${grayColour} En tu mejor momento has conseguido un total de${endColour}${greenColour} $maxmoney${endColour}"
      tput cnorm && exit 0
    fi
    
    let play_counter+=1
  done

  tput cnorm
}

while getopts "m:t:h" arg; do
  case $arg in
    m) money=$OPTARG;;
    t) technique=$OPTARG;; 
    h) helpPanel;;
  esac 
done
 
  if [ $money ] && [ "$technique" == "martingala" ]; then
    martingala
  else
    echo -e "\n${redColour}[!] La técnica elegidda no existe${endColour}"
    helpPanel
  fi



